@startuml
'https://plantuml.com/sequence-diagram

autonumber


User -> BackupManager: Adds a file to restore
User -> BackupManager: Creates BackupJob
BackupManager -> BackupJob: Created by manager
User -> BackupManager: Adds a file to restore
User -> BackupManager: Adds a file to restore
User -> BackupManager: Create RestorePoint
BackupManager -> BackupJob: Create RestorePoint
BackupJob -> RestorePoint1: Created by Job
BackupJob -> Server: Save Files
User -> BackupManager: Adds a file to restore
BackupManager -> BackupJob: Adds a file to restore
BackupJob -> RestorePoint2: Created by Job
User -> BackupManager: Save RestorePoint1
BackupManager -> BackupJob: Save RestorePoint1

BackupJob -> Server: Request to save 
@enduml